# Generated by Django 5.2.1 on 2025-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='badorder',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='badorder',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='badorder',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
