# Generated by Django 5.2.1 on 2025-05-24 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inventory_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
